Repository utilForever/CubbyFlow, pull requests merged in 2018-05, with the labels that each got.

#25 Add CI configuration (Travis CI / Appveyor) (#8)
  .travis.yml
  Scripts/travis_build.sh
  appveyor.yml
Labels: New Feature, Review

#27 Fixed segmentation fault for using C++11 Threads
  Includes/Core/Utils/Parallel-Impl.h
Labels: Bug, Review

#29 Add Docker system (#7)
  .travis.yml
  Dockerfile
  Scripts/travis_build_docker.sh
Labels: New Feature, Review

#32 Fix WARN_AS_ERROR_FLAGS and warning messages (#31)
  Builds/CMake/CompileOptions.cmake
  Sources/Core/Solver/Grid/GridFractionalSinglePhasePressureSolver2.cpp
  Tests/MemPerfTests/MemPerfTestsUtils.cpp
  Tests/MemPerfTests/MemPerfTestsUtils.h
  Tests/TimePerfTests/PointHashGridSearcher3Tests.cpp
  Tests/TimePerfTests/PointKdTreeSearcher3Tests.cpp
  Tests/TimePerfTests/PointParallelHashGridSearcher3Tests.cpp
Labels: Bug, Review

#33 Add code coverage tool (Codecov) (#9)
  .travis.yml
  Builds/CMake/CodeCoverage.cmake
  Builds/CMake/CompileOptions.cmake
  CMakeLists.txt
  Dockerfile
Labels: New Feature, Review

#35 Add code coverage additional features (#34)
  .codecov.yml
  README.md
Labels: Improvement, Review

#36 Add simple GUI system using imgui (#5)
  .travis.yml
  CMakeLists.txt
  Dockerfile
  Examples/ExampleHelper/CMakeLists.txt
  Examples/ExampleHelper/main.cpp
  Libraries/glfw/COPYING.txt
  Libraries/glfw/include/GLFW/glfw3.h
  Libraries/glfw/include/GLFW/glfw3native.h
  Libraries/glfw/lib/glfw3.dll
  Libraries/glfw/lib/glfw3.lib
  Libraries/imgui/CMakeLists.txt
  Libraries/imgui/imconfig.h
  Libraries/imgui/imgui.cpp
  Libraries/imgui/imgui.h
  Libraries/imgui/imgui_demo.cpp
  Libraries/imgui/imgui_draw.cpp
  Libraries/imgui/imgui_internal.h
  Libraries/imgui/stb_rect_pack.h
  Libraries/imgui/stb_textedit.h
  Libraries/imgui/stb_truetype.h
Labels: New Feature, Review
